name: PHP Insights
on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
        - uses: actions/checkout@v2
        - uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1

        - uses: actions/cache@v2
          with:
                path: vendor
                key: composer-${{ hashFiles('composer.lock') }}

        - run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader
        - run: composer install --prefer-dist --no-progress --no-suggest

        - run: vendor/bin/phpinsights -n --ansi --format=github-action
