name: Tests

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php modules routes tests database app
      # Commit styling changes
      # The reasoning behind the git pull, https://github.com/stefanzweifel/git-auto-commit-action/issues/209#issuecomment-1086681233
      - name: Pull Remote Changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling

    tests:
        needs: php-cs-fixer
        name: PHP Version ${{ matrix.php-versions }}
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                php-versions: [7.4|8.1]
                operating-system: [ubuntu-latest]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                php-version: ${{ matrix.php-versions }}
                extensions: mbstring, dom, fileinfo
                coverage: none

            # Install Composer Dependencies
            - name: Get composer cache directory
            id: composer-cache
            run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
            uses: actions/cache@v3
            with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
            run: |
                composer config -g github-oauth.github.com ${{ secrets.COMPOSER_OAUTH_GITHUB_ACTIONS }}
                composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run test suite
              run: composer test-all
